include:
  - local: 'ci/infra.gitlab-ci.yaml'
  - local: 'ci/app.gitlab-ci.yml'
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml

stages:
  - terraform
  - trigger
  - build
  - push
  - test
  - deploy
  - destroy