apiVersion: v1
kind: Service
metadata:
  name: testy-service
  labels:
    app: testy
spec:
  selector:
    app: testy
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8080
  type: NodePort
