terraform:
  stage: terraform
  image: google/cloud-sdk:latest
  rules:
    - changes:
        - infra/**/*
  before_script:
    - apt-get update && apt-get install -y wget unzip
    - wget https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    - unzip terraform_1.6.6_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - terraform -version
    - echo "$GCP_INFRA_KEY" | base64 -d > /tmp/gcp-key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
    - gcloud config set project "$GCP_PROJECT_ID"
    - gcloud config set compute/zone "$GCP_ZONE"
    - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json
  script:
    - cd infra
    - terraform init -input=false
    - terraform plan -out=tfplan
    - terraform apply -auto-approve tfplan 

trigger_app:
  stage: trigger
  trigger:
    include: ci/app.gitlab-ci.yml
    strategy: depend 
  rules:
    - changes:
        - infra/**/*     

destroy:
  stage: destroy
  image: cedricguadalupe/terraform-gcloud
  when: manual          
  allow_failure: false  
  before_script:
    - echo "$GCP_INFRA_KEY" | base64 -d > /tmp/gcp-key.json
    - gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
    - gcloud config set project "$GCP_PROJECT_ID"
    - gcloud config set compute/zone "$GCP_ZONE"
    - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json
  script:
    - cd infra
    - terraform init -input=false
    - terraform destroy -auto-approve
